font:
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal:
    style: "Medium"
    family: "Fira Code"

  # The bold font face
  bold:
    style: "Medium"
    family: "Fira Code"

  # The italic font face
  italic:
    style: "Medium Oblique"
    family: "Fira Code"

  # Point size of the font
  size: 16.0
colors:
  primary:
    background: '#000000'
    foreground: '#ffffff'
  normal:
    black:   '#000000'
    red:     '#ff8059'
    green:   '#44bc44'
    yellow:  '#d0bc00'
    blue:    '#2fafff'
    magenta: '#feacd0'
    cyan:    '#00d3d0'
    white:   '#bfbfbf'
  bright:
    black:   '#595959'
    red:     '#ef8b50'
    green:   '#70b900'
    yellow:  '#c0c530'
    blue:    '#79a8ff'
    magenta: '#b6a0ff'
    cyan:    '#6ae4b9'
    white:   '#ffffff'

key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
